   
name: test

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches:    
      - '*' 
jobs:
  Explore-GitHub-Actions:
   runs-on: self-hosted
   steps:
     - run: echo "testing testing"
